stageManager/manager/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Login
    path('', views.index, name='index'),
     path('logout/', views.deconexion, name='logout'),

    #Etudiant
    path('FiliereEtudiant/', views.filiereEtudiant, name='FiliereEtud'),
    path('newFiliere/', views.newFiliere, name='newFiliere'),
    path('home/<str:niveau>/<str:nom_filier>/<int:year>/<str:cin>', views.home, name='home'),
    path('newdossier/<str:niveau>/<str:nom_filier>/<int:year>/<str:cin>', views.newdossier, name='newdossier'),
    path('register/', views.register, name='register'),
    path('deleteFilier/<int:pk>/<str:niveau>/<int:year>', views.deleteFilier, name='deleteFilier'),
    path('afficherPdf/<int:id>/<int:n>', views.viewPdf, name='viewPdf'),
    
    
    #Prof
    path('homeProf/<str:niveau>/<str:nom_filier>/<int:annee>/<str:cin>', views.homeProf, name='homeProf'),
    path('delete/<int:pk>', views.deletedossier, name='deletedossier'),
    path('afficherdossier/<int:pk>', views.afficherdossier, name='afficherdossier'),
    path('updatedossier/<int:pk>', views.updatedossier, name='updatedossier'),
    path('filiereProf/', views.filiereProf, name='filiereProf'),
    path('etudiantsFil/<str:niveau>/<str:filiere>/<int:annee>', views.etudiantsFiliere, name='etudiantsFil'),
    
    
    
    #Admin
    path('filiereAdmin/', views.filieresAdmin, name='filiereAdmin'),

    path('ajoutFilierAdmin/', views.ajoutFilierAdmin, name='ajoutFilierAdmin'),
    path('updateFiliere/<int:pk>', views.updateFiliere, name='updateFiliere'),

    path('listEtudiants/<str:niveau>/<str:filiere>/<int:annee>/<str:prof>', views.listEtudiants, name='listEtudiants'),

    

    path('listeProfs/', views.listProfs, name='listProfs'),
    path('ajoutProf/', views.ajoutProf, name='ajoutProf'),
    path('updateProf/<int:pk>', views.updateProf, name='updateProf'),
    path('updateEtud/<int:pk>', views.updateEtud, name='updateEtud'),
    path('deleteProf/<int:pk>', views.deleteProf, name='deleteProf'),
    path('deleteEtud/<int:pk>', views.deleteEtud, name='deleteEtud'),
    path('afficherProf/<int:pk>', views.afficherProf, name='afficherProf'),

    path('listDossiers/<str:niveau>/<str:filiere>/<int:annee>/<str:encadrant>/<str:prof>', views.listDossiers, name='listDossiers'),

    path('afficherDossierAdmin/<int:pk>/<str:prof>', views.afficherDossierAdmin, name='afficherDossierAdmin'),
    path("deleteFiliere/<int:pk>", views.deleteFiliere, name="deleteFiliere"),
    path("newfiliereAdmin/<int:pk>", views.newfiliereAdmin, name="newfiliereAdmin"),
    path('deleteSession/<int:id>', views.deleteSession, name='deleteSession'),
    path('updateSession/<str:niveau>/<str:filiere>/<int:annee>/<str:prof>', views.updateSession, name='updateSession'),
    path('domainesFilière/<str:nomFiliere>', views.domainesAdmin, name="domainesAdmin"),
    path('deleteDomaine/<str:nomFiliere>/<int:pk>', views.deleteDomaine, name='deleteDomaine'),
    path('importerEtud', views.importerEtud, name='importerEtud'),
    path('listEtuds', views.listEtuds, name='listEtuds'),
    path('afficherEtud/<int:pk>', views.afficherEtud, name='afficherEtud'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stageManager/stageManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls'))
]

stageManager/manager/models.py
from typing import Iterable
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
import os


class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN="ADMIN", 'ADMIN'
        PROF="PROF", 'PROF'
        ETUDIANT="ETUDIANT", 'ETUDIANT'
    SEX = (
        ("Male", "Male"),
        ('Female', 'Female'),
    )
    base_role=Role.ADMIN
    base_role1=Role.ETUDIANT
    role = models.CharField(max_length = 20, choices= Role)
     
    Sex =  models.CharField(max_length = 10, choices=SEX)
    #adresse
    adresse=models.TextField(max_length=150,null=True)
    #tel
    tel=models.CharField(max_length=40,null=True)

    #N_apog
    Napog=models.IntegerField(default=0,null=True)
    #CNE
    CNE=models.CharField(max_length=50,null=True)
    #date_n
    dateN= models.DateField(auto_now=False, auto_now_add=False, null=True)
    #lieux_n
    lieuxN = models.CharField(max_length=50,null=True)
    
    
    #spc
    SPC = models.CharField(max_length = 50,null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role=self.base_role
            return super().save(*args, **kwargs)
        else:
            return super().save(*args, **kwargs)


class ProfManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        result=super().get_queryset(*args, **kwargs)
        return result.filter(role=User.Role.PROF)
        
class Prof(User):
    base_role=User.Role.PROF
    prof=ProfManager()
    class Meta:
        proxy=True


class StudentManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        result=super().get_queryset(*args, **kwargs)
        return result.filter(role=User.Role.ETUDIANT)
    
class Student(User):
    base_role=User.Role.ETUDIANT
    student=StudentManager()
    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)
    class Meta:
        proxy=True

def pdf1_upload_to(instance, filename):
    return os.path.join('rapports', f'{instance.Student.username}', filename)

def pdf2_upload_to(instance, filename):
    return os.path.join('dossiers', f'{instance.Student.username}', filename)

class Dossiers(models.Model):
    TYPES = (
        ("1", "Stage d'initiation"),
        ('2', 'stage technique'),
        ('3', 'stage PFE'),
        ('4', 'Stage Professionel'),
    )
    NIVEAUX = (
        ("1ere Annee", "1ere Annee"),
        ("2eme Annee", "2eme Annee"),
        ('Licence Professionelle', 'Licence Professionelle'),
    )
    Type = models.CharField(max_length=50, choices=TYPES)
    Rapport = models.FileField(upload_to=pdf1_upload_to)
    Doss= models.FileField(upload_to=pdf2_upload_to)
    Sujet = models.CharField(max_length=100, null=False, blank=False)
    Encadrant = models.CharField(max_length=100, null=False, blank=False)
    Domaine = models.CharField(max_length=100, null=False, blank=False)

    Nom_filiere = models.CharField(max_length=100)
    Year = models.DateField(auto_now=False, auto_now_add=False)
    Niveau = models.CharField(max_length=50, choices = NIVEAUX)

    Student = models.ForeignKey(Student, on_delete=models.CASCADE)

    ValidationProf = models.BooleanField(default=False)
    ValidationAdmin = models.BooleanField(default=False)
    RemarqueProf = models.CharField(max_length=255, blank=True, null=True)
    RemarqueAdmin = models.CharField(max_length=255, blank=True, null=True)
    class Meta:
        ordering=['Type']
    
    def __str__(self):
        return f"{self.Sujet} {self.Domaine}"

class Filiere(models.Model):
    Nom_filiere = models.CharField(max_length=100, unique=True) 
    def __str__(self):
        return f"{self.Nom_filiere}"


class StudenttFiliere(models.Model):
    NIVEAUX = (
        ("1ere Annee", "1ere Annee"),
        ("2eme Annee", "2eme Annee"),
        ('Licence Professionelle', 'Licence Professionelle'),
    )
    Niveau = models.CharField(max_length=50 , choices = NIVEAUX, null=False)
    Year = models.DateField(auto_now=False, auto_now_add=False, null=False)
    Etudiant = models.ForeignKey(Student, on_delete=models.DO_NOTHING, null=False)
    Filiere = models.ForeignKey(Filiere, on_delete=models.DO_NOTHING, null=False)
    class Meta:
        unique_together = ( 'Year', 'Etudiant')
        ordering = ['Year']
    def __str__(self):
        return f"{self.Etudiant.username}--{self.Filiere.Nom_filiere}--{self.Niveau} -- {self.Year.year}"

class Prof_Filiere(models.Model):
    NIVEAUX = (
        ("1ere Annee", "1ere Annee"),
        ("2eme Annee", "2eme Annee"),
        ('Licence Professionelle', 'Licence Professionelle'),
    )
    Niveau = models.CharField(max_length=50 , choices = NIVEAUX, null=False)
    prof = models.ForeignKey(Prof, on_delete=models.DO_NOTHING)
    filiere = models.ForeignKey(Filiere, on_delete=models.DO_NOTHING)
    Annee = models.DateField(auto_now=False, auto_now_add=False,  null=False)
    class Meta:
        unique_together = ('Niveau', 'filiere', 'prof', 'Annee')
        ordering = ['Annee', 'prof', 'Niveau']

    def __str__(self):
        return f'{self.prof.username}--{self.Niveau}--{self.filiere.Nom_filiere}'

class Domaine(models.Model):
    NomDomaine = models.CharField(max_length=100) 
    filiere = models.ForeignKey( Filiere , on_delete=models.CASCADE)
    def __str__(self):
        return self.NomDomaine







  

stageManager/templates/manager/AfficherEtud.html
{% extends 'manager/base.html' %} 
{% block content %}
<div class="form container">
  <h3>Etudiant</h3>

  <div class="mb-3 row">
    <label for="N" class="col-sm-2 col-form-label">N° apogée</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="N" name="Napog" value="{{ Etudiant.Napog }}" disabled />
    </div>
  </div>

    <div class="mb-3 row">
      <label for="CIN" class="col-sm-2 col-form-label">CINE</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="CIN" name="CIN" value="{{ Etudiant.username }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="CIN" class="col-sm-2 col-form-label">CNE</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="CIN" name="CIN" value="{{ Etudiant.CNE }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Sex" class="col-sm-2 col-form-label">Sex</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Sex" name="Sex" value="{{ Etudiant.Sex }}" disabled />
      </div>
    </div>



    <div class="mb-3 row">
      <label for="Nom" class="col-sm-2 col-form-label">Nom de famille</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Nom" name="Nom" value="{{ Etudiant.last_name }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Prenom" class="col-sm-2 col-form-label">Prénom</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="prenom" name="prenom" value="{{ Etudiant.first_name  }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="adresse" class="col-sm-2 col-form-label">Adresse</label>
      <div class="col-sm-10">
        <textarea class="form-control" id="adresse" rows="3" name="adresse" value="" disabled>{{ Etudiant.adresse }}</textarea>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="tel" class="col-sm-2 col-form-label" >Téléphone</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="tel" name="tel" value="{{ Etudiant.tel }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="DateN" class="col-sm-2 col-form-label">Date de naissance</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="DateN" name="DateN" value="{{ Etudiant.dateN|date:'d-m-Y' }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="LieuxN" class="col-sm-2 col-form-label">Lieux de naissance</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="LieuxN" name="LieuxN" value="{{ Etudiant.lieuxN }}" disabled />
      </div>
    </div>

      <div class="mb-3 row">
        <div class="col-12">
        <a class="form-control btn btn-primary" href="{% url 'listEtuds' %}">Retour</a>
        </div>
      </div>
</div>
{% endblock content %}

stageManager/templates/manager/afficherDossierAdmin.html
{% extends 'manager/base.html' %} 

{% block content %}
<div class="form container">
    <h3>Dossier de l'etudiant {{ dossier.Student.username }}-{{ dossier.Student.last_name }} {{ dossier.Student.first_name }} </h3>

  <hr>
      <div class="mb-3 row">
        <label for="Type" class="col-sm-2 col-form-label">Type</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="Type" name="Type" value= "{{ dossier.get_Type_display }}" disabled/>
        </div>
      </div>
     
    <div class="mb-3 row">
      
      <label for="Rapport" class="col-sm-2 col-form-label">Lien Rapport</label>
      
      <div class="input-group col-sm-10">
        <input type="text" class="form-control" id="Rapport" name="Rapport" value="{{ dossier.Rapport }}" disabled/>
        <a target="_blank" class="btn btn-outline-success" type="button" href="{% url 'viewPdf' dossier.id 1 %}">Ouvrir</a>
      </div>

   
    </div>

    <div class="mb-3 row">

      <label for="Dossier" class="col-sm-2 col-form-label">Lien Dossier</label>

      <div class="input-group col-sm-10">
        <input type="text" class="form-control" id="Dossier" name="Dossier" value="{{ dossier.Doss }}" disabled/>
        <a target="_blank" class="btn btn-outline-success" type="button" href="{% url 'viewPdf' dossier.id 2 %}">Ouvrir</a>
      </div>
      
    </div>

    <div class="mb-3 row">
      <label for="Sujet" class="col-sm-2 col-form-label">Sujet</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Sujet" name="Sujet" value="{{ dossier.Sujet }}" disabled/>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Encadrant" class="col-sm-2 col-form-label">Encadrant</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Encadrant" name="Encadrant" value="{{ dossier.Encadrant }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Domaine" class="col-sm-2 col-form-label">Domaine</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Domaine" name="Domaine" value="{{ dossier.Domaine }}" disabled />
      </div>
    </div>

    <form action="{% url 'afficherDossierAdmin' dossier.pk prof %}" method="POST">
    {% csrf_token %}

    <div class="mb-3 row">
      <label for="validationp" class="col-sm-2 col-form-label">Validation du prof</label>
      <div class="col-sm-10">
        <input class="form-check-input"  type="checkbox" name="val" {% if dossier.ValidationProf %} checked  {% endif %} disabled >
      </div>
    </div>
   
    {% if not dossier.ValidationProf %} 
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Remarque du prof</label>
      <div class="col-sm-10">
        <input class="form-control"  type="textfield" {% if dossier.RemarqueProf is None %} value=""  {% else %} value="{{ dossier.RemarqueProf }}"{% endif %} name="remarqProf" disabled >
      </div>
    </div>
    {% endif %}
    
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Validation d'admin</label>
      <div class="col-sm-10">
        <input class="form-check-input" id="chek1" name="valA" type="checkbox" {% if dossier.ValidationAdmin %} checked {% endif %}>
      </div>
    </div>

    {% if not dossier.ValidationAdmin %} 
    <div class="mb-3 row">
      <label for="validationa" id="labelA" class="col-sm-2 col-form-label">Remarque d'admin</label>
      <div class="col-sm-10">
        <input class= "form-control" id="valifdationA" name="remarqAdmin" type="textfield" {% if dossier.RemarqueAdmin is None %} value=""  {% else %} value="{{ dossier.RemarqueAdmin }}"{% endif %} {% if dossier.RemarqueProf is None %} value=""  {% else %} value="{{ dossier.RemarqueProf }}"{% endif %}>
      </div>
    </div>
    {% endif %}

    <script>
        const checkInput = document.getElementById('chek1');
        const textInput = document.getElementById('valifdationA');
      
        const label = document.getElementById('labelA');

        checkInput.addEventListener('change', function() {
        if(this.checked) {
            textInput.value = ''; 
            textInput.style.display = 'none';
            label.style.display = 'none';
        } 
        else {
            textInput.style.display = 'block';
            label.style.display = 'block';
        }
        });
      </script>


    {% if request.user.role == 'PROF' or request.user.role == 'ADMIN' %}
      <div class="d-grid gap-2">
        <button class="btn btn-primary" type="submit">Enregistrer le dossier</a>
      </div>
    {% endif %}
  </form>
    
    <div class="d-grid gap-2">
      <a class="btn btn-success mt-2" href="{% url 'listDossiers' dossier.Niveau dossier.Nom_filiere dossier.Year.year dossier.Encadrant prof %}">Retour</a>
    </div>
</div>

{% endblock content %}

stageManager/templates/manager/afficherdossier.html
{% extends 'manager/base.html' %} 

{% block content %}
<div class="form container">
  {% if request.user.role == 'ETUDIANT' %}
    <h3>Voici votre dossier</h3>
  {% elif request.user.role == 'PROF' %}
    <h3>Dossier de l'etudiant {{ Etudiant.username }}-{{ Etudiant.last_name }} {{ Etudiant.first_name }} </h3>
  {% endif %}
  <hr>
      <div class="mb-3 row">
        <label for="Type" class="col-sm-2 col-form-label">Type</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="Type" name="Type" value= "{{ dossier.get_Type_display }}" disabled/>
        </div>
      </div>
     
    <div class="mb-3 row">
      
      <label for="Rapport" class="col-sm-2 col-form-label">Lien Rapport</label>
      
      <div class="input-group col-sm-10">
        <input type="text" class="form-control" id="Rapport" name="Rapport" value="{{ dossier.Rapport }}" disabled/>
        <a target="_blank" class="btn btn-outline-success" type="button" href="{% url 'viewPdf' dossier.id 1 %}">Ouvrir</a>
      </div>
    </div>

    <div class="mb-3 row">

      <label for="Dossier" class="col-sm-2 col-form-label">Lien Dossier</label>

      <div class="input-group col-sm-10">
        <input type="text" class="form-control" id="Dossier" name="Dossier" value="{{ dossier.Doss }}" disabled/>
        <a target="_blank" class="btn btn-outline-success" type="button" href="{% url 'viewPdf' dossier.id 2 %}">Ouvrir</a>
      </div>
      
    </div>

    <div class="mb-3 row">
      <label for="Sujet" class="col-sm-2 col-form-label">Sujet</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Sujet" name="Sujet" value="{{ dossier.Sujet }}" disabled/>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Encadrant" class="col-sm-2 col-form-label">Encadrant</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Encadrant" name="Encadrant" value="{{ dossier.Encadrant }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Domaine" class="col-sm-2 col-form-label">Domaine</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Domaine" name="Domaine" value="{{ dossier.Domaine }}" disabled />
      </div>
    </div>

    <form action="{% url 'afficherdossier' dossier.pk %}" method="POST">
    {% csrf_token %}

    <div class="mb-3 row">
      <label for="validationp" class="col-sm-2 col-form-label">Validation du prof</label>
      <div class="col-sm-10">
        <input class="form-check-input" id="chek1" type="checkbox" name="val" {% if checked %} checked  {% endif %} {% if request.user.role == "ETUDIANT" %} disabled {% endif %}>
      </div>
    </div>
   
    {% if not dossier.ValidationProf %} 
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Remarque du prof</label>
      <div class="col-sm-10">
        <input class="form-control" id="valifdationp" type="textfield" {% if dossier.RemarqueProf is None %} value=""  {% else %} value="{{ dossier.RemarqueProf }}"{% endif %} name="remarqProf" {% if request.user.role == "ETUDIANT" %} disabled {% endif %}>
      </div>
    </div>
    {% endif %}
    <script>
      const checkInput = document.getElementById('chek1');
      const textInput = document.getElementById('valifdationp');
    
      checkInput.addEventListener('change', function() {
      if(this.checked) {
          textInput.value = ''; 
          textInput.style.display = 'none';
      } 
      else {
          textInput.style.display = 'block';
      }
      });
    </script>
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Validation d'admin</label>
      <div class="col-sm-10">
        <input class="form-check-input"  type="checkbox" {% if dossier.ValidationAdmin %} checked {% endif %}  disabled >
      </div>
    </div>

    {% if not dossier.ValidationAdmin %} 
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Remarque d'admin</label>
      <div class="col-sm-10">
        <input class= "form-control" type="textfield" value="{{ dossier.RemarqueAdmin }}"  disabled>
      </div>
    </div>
    {% endif %}

    {% if request.user.role == 'PROF' %}
      <div class="d-grid gap-2">
        <button class="btn btn-primary" type="submit">Enregistrer le dossier</a>
      </div>
    {% endif %}
  </form>
    
    <div class="d-grid gap-2">
      <a class="btn btn-success mt-2" href="{% url 'home' dossier.Niveau dossier.Nom_filiere dossier.Year.year dossier.Student.username %}">Retour</a>
    </div>
</div>

{% endblock content %}

stageManager/templates/manager/afficherdossierProf.html
{% extends 'manager/base.html' %} 

{% block content %}
<div class="form container">
  {% if request.user.role == 'ETUDIANT' %}
    <h3>Voici votre dossier</h3>
  {% elif request.user.role == 'PROF' %}
    <h3>Dossier de l'etudiant {{ Etudiant.username }}-{{ Etudiant.last_name }} {{ Etudiant.first_name }} </h3>
  {% endif %}
  <hr>
      <div class="mb-3 row">
        <label for="Type" class="col-sm-2 col-form-label">Type</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="Type" name="Type" value= "{{ dossier.get_Type_display }}" disabled/>
        </div>
      </div>
     
    <div class="mb-3 row">
      
      <label for="Rapport" class="col-sm-2 col-form-label">Lien Rapport</label>
      
      <div class="input-group col-sm-10">
        <input type="text" class="form-control" id="Rapport" name="Rapport" value="{{ dossier.Rapport }}" disabled/>
        <a target="_blank" class="btn btn-outline-success" type="button" href="{% url 'viewPdf' dossier.id 1 %}">Ouvrir</a>
      </div>

   
    </div>

    <div class="mb-3 row">

      <label for="Dossier" class="col-sm-2 col-form-label">Lien Dossier</label>

      <div class="input-group col-sm-10">
        <input type="text" class="form-control" id="Dossier" name="Dossier" value="{{ dossier.Doss }}" disabled/>
        <a target="_blank" class="btn btn-outline-success" type="button" href="{% url 'viewPdf' dossier.id 2 %}">Ouvrir</a>
      </div>
      
    </div>

    <div class="mb-3 row">
      <label for="Sujet" class="col-sm-2 col-form-label">Sujet</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Sujet" name="Sujet" value="{{ dossier.Sujet }}" disabled/>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Encadrant" class="col-sm-2 col-form-label">Encadrant</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Encadrant" name="Encadrant" value="{{ dossier.Encadrant }}" disabled />
      </div>
    </div>

    <div class="mb-3 row">
      <label for="Domaine" class="col-sm-2 col-form-label">Domaine</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="Domaine" name="Domaine" value="{{ dossier.Domaine }}" disabled />
      </div>
    </div>

    <form action="{% url 'afficherdossier' dossier.pk %}" method="POST">
    {% csrf_token %}

    <div class="mb-3 row">
      <label for="validationp" class="col-sm-2 col-form-label">Validation du prof</label>
      <div class="col-sm-10">
        <input class="form-check-input" id="chek1" type="checkbox" name="val" {% if checked %} checked  {% endif %} {% if request.user.role == "ETUDIANT" %} disabled {% endif %}>
      </div>
    </div>
   
    {% if not dossier.ValidationProf %} 
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Remarque du prof</label>
      <div class="col-sm-10">
        <input class="form-control" id="valifdationp" type="textfield" {% if dossier.RemarqueProf is None %} value=""  {% else %} value="{{ dossier.RemarqueProf }}"{% endif %} name="remarqProf" {% if request.user.role == "ETUDIANT" %} disabled {% endif %}>
      </div>
    </div>
    {% endif %}
    <script>
      const checkInput = document.getElementById('chek1');
      const textInput = document.getElementById('valifdationp');
    
      checkInput.addEventListener('change', function() {
      if(this.checked) {
          textInput.value = ''; 
          textInput.style.display = 'none';
      } 
      else {
          textInput.style.display = 'block';
      }
      });
    </script>
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Validation d'admin</label>
      <div class="col-sm-10">
        <input class="form-check-input"  type="checkbox" {% if dossier.ValidationAdmin %} checked {% endif %}  disabled >
      </div>
    </div>

    {% if not dossier.ValidationAdmin %} 
    <div class="mb-3 row">
      <label for="validationa" class="col-sm-2 col-form-label">Remarque d'admin</label>
      <div class="col-sm-10">
        <input class= "form-control" type="textfield" value="{{ dossier.RemarqueAdmin }}" {% if dossier.RemarqueAdmin is None %} value=""  {% else %} value="{{ dossier.RemarqueAdmin }}"{% endif %}  disabled>
      </div>
    </div>
    {% endif %}

    {% if request.user.role == 'PROF' %}
      <div class="d-grid gap-2">
        <button class="btn btn-primary" type="submit">Enregistrer le dossier</a>
      </div>
    {% endif %}
  </form>
  <div class="my-2 d-grid gap-2">
    <a class="btn btn-success mt-2" href="{% url 'homeProf' niveau nom_filier annee cin %}">Retour</a>
  </div>
</div>

{% endblock content %}